AppBundle\Entity\Curso:
  properties:
    titulo:
      - NotBlank: { message: "El titulo no puede estar vacio" }
      - Length:
         min: 2
         minMessage: El titulo debe tener mas de dos caracteres
    descripcion:
      - NotBlank: { message: "El titulo no puede estar vacio" }
    precio:
      - Type:
         type: numeric
         message: El valor debe ser solo numeros